# Use the official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /employee-app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install NestJS dependencies
RUN npm install --force

# Copy the rest of the application code to the container
COPY . .

# Expose the port that your NestJS application listens on (e.g., 3000)
# EXPOSE 3001

# Define the command to start your NestJS application
CMD [ "npm", "start" ]